// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EndTask():Promise<boolean>;

export function GetGUIConfig():Promise<main.GUIConfig>;

export function GetMemoryView():Promise<main.MemoryView>;

export function SaveGUIConfig(arg1:main.GUIConfig):Promise<void>;

export function SendLine(arg1:string):Promise<void>;
