// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbandonBoundary() {
  return window['go']['main']['App']['AbandonBoundary']();
}

export function AddPane() {
  return window['go']['main']['App']['AddPane']();
}

export function AmendExperience(arg1) {
  return window['go']['main']['App']['AmendExperience'](arg1);
}

export function ChooseDirectory(arg1, arg2) {
  return window['go']['main']['App']['ChooseDirectory'](arg1, arg2);
}

export function ClosePane(arg1) {
  return window['go']['main']['App']['ClosePane'](arg1);
}

export function EndTask(arg1) {
  return window['go']['main']['App']['EndTask'](arg1);
}

export function ForgetExperiences(arg1) {
  return window['go']['main']['App']['ForgetExperiences'](arg1);
}

export function GetGUIConfig() {
  return window['go']['main']['App']['GetGUIConfig']();
}

export function GetMemoryView() {
  return window['go']['main']['App']['GetMemoryView']();
}

export function GetPanes() {
  return window['go']['main']['App']['GetPanes']();
}

export function GetSessionDigest(arg1) {
  return window['go']['main']['App']['GetSessionDigest'](arg1);
}

export function GetSessionScrollback(arg1) {
  return window['go']['main']['App']['GetSessionScrollback'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSpriteSheet() {
  return window['go']['main']['App']['GetSpriteSheet']();
}

export function GetTomoStatus() {
  return window['go']['main']['App']['GetTomoStatus']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SaveGUIConfig(arg1) {
  return window['go']['main']['App']['SaveGUIConfig'](arg1);
}

export function SendLine(arg1, arg2) {
  return window['go']['main']['App']['SendLine'](arg1, arg2);
}

export function SetVerdict(arg1, arg2) {
  return window['go']['main']['App']['SetVerdict'](arg1, arg2);
}

export function SetWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWorkspace'](arg1, arg2, arg3);
}
