// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AmendExperience(arg1:main.AmendRequest):Promise<main.WriteResult>;

export function EndTask():Promise<boolean>;

export function ForgetExperiences(arg1:Array<string>):Promise<main.WriteResult>;

export function GetGUIConfig():Promise<main.GUIConfig>;

export function GetMemoryView():Promise<main.MemoryView>;

export function GetSessionDigest(arg1:string):Promise<main.SessionDetail>;

export function GetSessions():Promise<main.SessionList>;

export function GetTomoStatus():Promise<main.TomoStatus>;

export function SaveGUIConfig(arg1:main.GUIConfig):Promise<void>;

export function SendLine(arg1:string):Promise<void>;
