// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbandonBoundary() {
  return window['go']['main']['App']['AbandonBoundary']();
}

export function AmendExperience(arg1) {
  return window['go']['main']['App']['AmendExperience'](arg1);
}

export function ChooseDirectory(arg1, arg2) {
  return window['go']['main']['App']['ChooseDirectory'](arg1, arg2);
}

export function EndTask() {
  return window['go']['main']['App']['EndTask']();
}

export function ForgetExperiences(arg1) {
  return window['go']['main']['App']['ForgetExperiences'](arg1);
}

export function GetGUIConfig() {
  return window['go']['main']['App']['GetGUIConfig']();
}

export function GetMemoryView() {
  return window['go']['main']['App']['GetMemoryView']();
}

export function GetSessionDigest(arg1) {
  return window['go']['main']['App']['GetSessionDigest'](arg1);
}

export function GetSessionScrollback(arg1) {
  return window['go']['main']['App']['GetSessionScrollback'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetTomoStatus() {
  return window['go']['main']['App']['GetTomoStatus']();
}

export function QuitNow() {
  return window['go']['main']['App']['QuitNow']();
}

export function SaveGUIConfig(arg1) {
  return window['go']['main']['App']['SaveGUIConfig'](arg1);
}

export function SendLine(arg1) {
  return window['go']['main']['App']['SendLine'](arg1);
}

export function SetWorkspace(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspace'](arg1, arg2);
}
