// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndTask() {
  return window['go']['main']['App']['EndTask']();
}

export function GetGUIConfig() {
  return window['go']['main']['App']['GetGUIConfig']();
}

export function GetMemoryView() {
  return window['go']['main']['App']['GetMemoryView']();
}

export function SaveGUIConfig(arg1) {
  return window['go']['main']['App']['SaveGUIConfig'](arg1);
}

export function SendLine(arg1) {
  return window['go']['main']['App']['SendLine'](arg1);
}
